version: '3.3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPassword}
      - POSTGRES_DB=${DBName}

    ports:
      - "${DBPort}:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    container_name: postgres
    networks:
      aappanavypar-backend:


  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    container_name: pg_admmin
    networks:
      aappanavypar-frountend:
      aappanavypar-backend:


  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: redis_cash
    networks:
      aappanavypar-backend:


  app:
    build: .
    ports:
      - "4356:8080"
    restart: on-failure
    depends_on:
      - postgres
      - redis
    container_name: app
    command: ["./start.sh"]
    networks:
      aappanavypar-frountend:
      aappanavypar-backend:

# Custom network so all services can communicate using a FQDN
networks:
    aappanavypar-frountend:
    aappanavypar-backend:

